// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// idxstats
Rcpp::DataFrame idxstats(std::string bam_file);
RcppExport SEXP genomation_idxstats(SEXP bam_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type bam_file(bam_fileSEXP);
    __result = Rcpp::wrap(idxstats(bam_file));
    return __result;
END_RCPP
}
