// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// binMean
NumericVector binMean(NumericVector x, int n);
RcppExport SEXP genomation_binMean(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binMean(x, n));
    return rcpp_result_gen;
END_RCPP
}
// binMedian
NumericVector binMedian(NumericVector x, int n);
RcppExport SEXP genomation_binMedian(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binMedian(x, n));
    return rcpp_result_gen;
END_RCPP
}
// binMax
NumericVector binMax(NumericVector x, int n);
RcppExport SEXP genomation_binMax(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binMax(x, n));
    return rcpp_result_gen;
END_RCPP
}
// binMin
NumericVector binMin(NumericVector x, int n);
RcppExport SEXP genomation_binMin(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binMin(x, n));
    return rcpp_result_gen;
END_RCPP
}
// binSum
NumericVector binSum(NumericVector x, int n);
RcppExport SEXP genomation_binSum(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binSum(x, n));
    return rcpp_result_gen;
END_RCPP
}
// reverse_L
NumericVector reverse_L(NumericVector y);
RcppExport SEXP genomation_reverse_L(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(reverse_L(y));
    return rcpp_result_gen;
END_RCPP
}
// listSliceMean
NumericMatrix listSliceMean(List xlist, int n, CharacterVector ranks);
RcppExport SEXP genomation_listSliceMean(SEXP xlistSEXP, SEXP nSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(listSliceMean(xlist, n, ranks));
    return rcpp_result_gen;
END_RCPP
}
// listSliceMedian
NumericMatrix listSliceMedian(List xlist, int n, CharacterVector ranks);
RcppExport SEXP genomation_listSliceMedian(SEXP xlistSEXP, SEXP nSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(listSliceMedian(xlist, n, ranks));
    return rcpp_result_gen;
END_RCPP
}
// listSliceMax
NumericMatrix listSliceMax(List xlist, int n, CharacterVector ranks);
RcppExport SEXP genomation_listSliceMax(SEXP xlistSEXP, SEXP nSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(listSliceMax(xlist, n, ranks));
    return rcpp_result_gen;
END_RCPP
}
// listSliceMin
NumericMatrix listSliceMin(List xlist, int n, CharacterVector ranks);
RcppExport SEXP genomation_listSliceMin(SEXP xlistSEXP, SEXP nSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(listSliceMin(xlist, n, ranks));
    return rcpp_result_gen;
END_RCPP
}
// listSliceSum
NumericMatrix listSliceSum(List xlist, int n, CharacterVector ranks);
RcppExport SEXP genomation_listSliceSum(SEXP xlistSEXP, SEXP nSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(listSliceSum(xlist, n, ranks));
    return rcpp_result_gen;
END_RCPP
}
// ranksOrder
NumericMatrix ranksOrder(NumericMatrix x, NumericVector p);
RcppExport SEXP genomation_ranksOrder(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(ranksOrder(x, p));
    return rcpp_result_gen;
END_RCPP
}
// matRes
NumericMatrix matRes(List xlist, int n, CharacterVector negranks, std::string binOp, NumericVector p);
RcppExport SEXP genomation_matRes(SEXP xlistSEXP, SEXP nSEXP, SEXP negranksSEXP, SEXP binOpSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type xlist(xlistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type negranks(negranksSEXP);
    Rcpp::traits::input_parameter< std::string >::type binOp(binOpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(matRes(xlist, n, negranks, binOp, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"genomation_binMean", (DL_FUNC) &genomation_binMean, 2},
    {"genomation_binMedian", (DL_FUNC) &genomation_binMedian, 2},
    {"genomation_binMax", (DL_FUNC) &genomation_binMax, 2},
    {"genomation_binMin", (DL_FUNC) &genomation_binMin, 2},
    {"genomation_binSum", (DL_FUNC) &genomation_binSum, 2},
    {"genomation_reverse_L", (DL_FUNC) &genomation_reverse_L, 1},
    {"genomation_listSliceMean", (DL_FUNC) &genomation_listSliceMean, 3},
    {"genomation_listSliceMedian", (DL_FUNC) &genomation_listSliceMedian, 3},
    {"genomation_listSliceMax", (DL_FUNC) &genomation_listSliceMax, 3},
    {"genomation_listSliceMin", (DL_FUNC) &genomation_listSliceMin, 3},
    {"genomation_listSliceSum", (DL_FUNC) &genomation_listSliceSum, 3},
    {"genomation_ranksOrder", (DL_FUNC) &genomation_ranksOrder, 2},
    {"genomation_matRes", (DL_FUNC) &genomation_matRes, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_genomation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
