// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// idxStats
Rcpp::DataFrame idxStats(std::string bam_file);
RcppExport SEXP genomation_idxStats(SEXP bam_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_file(bam_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(idxStats(bam_file));
    return rcpp_result_gen;
END_RCPP
}
