# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast retrieval of indexstats
#' 
#' Retrieve and print stats in the index file corresponding 
#' to the input file. Before calling idxstats, the input BAM file
#' must be indexed, e.g. via samtools index.
#' 
#' @param bam_file path to the indexed BAM file 
#' @export 
idxStats <- function(bam_file) {
    .Call('genomation_idxStats', PACKAGE = 'genomation', bam_file)
}

