# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Functions that compute the value for each bin
#'
#' binMean() computes a mean value, binMedian() computes a median value, binMax() and binMin() 
#' give maximum and minumum values respectively, binSum() computes the sum of the values in a bin
#'
#' @param x NumericVector - vector of values of a bin
#' @param n intiger - number of bins
#' @export
#' @rdname bin
binMean <- function(x, n) {
    .Call('genomation_binMean', PACKAGE = 'genomation', x, n)
}

#' @export
#' @rdname bin
binMedian <- function(x, n) {
    .Call('genomation_binMedian', PACKAGE = 'genomation', x, n)
}

#' @export
#' @rdname bin
binMax <- function(x, n) {
    .Call('genomation_binMax', PACKAGE = 'genomation', x, n)
}

#' @export
#' @rdname bin
binMin <- function(x, n) {
    .Call('genomation_binMin', PACKAGE = 'genomation', x, n)
}

#' @export
#' @rdname bin
binSum <- function(x, n) {
    .Call('genomation_binSum', PACKAGE = 'genomation', x, n)
}

#' Functions create a matrix storing the data with desirable number of bins for each window 
#'
#' listSliceMean() calls the binMean() function, listSliceMedian calls the binMedian(), 
#' listSliceMax() - binMax(), listSliceMin() - binMin(), listSliceSum() - binSum()
#'
#' @param xlist List of vectors storing values of a bin
#' @param n intiger - number of bins
#' @export
#' @rdname listSlice
listSliceMean <- function(xlist, n) {
    .Call('genomation_listSliceMean', PACKAGE = 'genomation', xlist, n)
}

#' @export
#' @rdname listSlice
listSliceMedian <- function(xlist, n) {
    .Call('genomation_listSliceMedian', PACKAGE = 'genomation', xlist, n)
}

#' @export
#' @rdname listSlice
listSliceMax <- function(xlist, n) {
    .Call('genomation_listSliceMax', PACKAGE = 'genomation', xlist, n)
}

#' @export
#' @rdname listSlice
listSliceMin <- function(xlist, n) {
    .Call('genomation_listSliceMin', PACKAGE = 'genomation', xlist, n)
}

#' @export
#' @rdname listSlice
listSliceSum <- function(xlist, n) {
    .Call('genomation_listSliceSum', PACKAGE = 'genomation', xlist, n)
}

