# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binMean <- function(x, n) {
    .Call('genomation_binMean', PACKAGE = 'genomation', x, n)
}

binMedian <- function(x, n) {
    .Call('genomation_binMedian', PACKAGE = 'genomation', x, n)
}

binMax <- function(x, n) {
    .Call('genomation_binMax', PACKAGE = 'genomation', x, n)
}

binMin <- function(x, n) {
    .Call('genomation_binMin', PACKAGE = 'genomation', x, n)
}

binSum <- function(x, n) {
    .Call('genomation_binSum', PACKAGE = 'genomation', x, n)
}

reverse_L <- function(y) {
    .Call('genomation_reverse_L', PACKAGE = 'genomation', y)
}

listSliceMean <- function(xlist, n, ranks) {
    .Call('genomation_listSliceMean', PACKAGE = 'genomation', xlist, n, ranks)
}

listSliceMedian <- function(xlist, n, ranks) {
    .Call('genomation_listSliceMedian', PACKAGE = 'genomation', xlist, n, ranks)
}

listSliceMax <- function(xlist, n, ranks) {
    .Call('genomation_listSliceMax', PACKAGE = 'genomation', xlist, n, ranks)
}

listSliceMin <- function(xlist, n, ranks) {
    .Call('genomation_listSliceMin', PACKAGE = 'genomation', xlist, n, ranks)
}

listSliceSum <- function(xlist, n, ranks) {
    .Call('genomation_listSliceSum', PACKAGE = 'genomation', xlist, n, ranks)
}

ranksOrder <- function(x, p) {
    .Call('genomation_ranksOrder', PACKAGE = 'genomation', x, p)
}

